In [40]:
import keras_ocr
import numpy as np
import matplotlib.pyplot as plt

In [41]:
pipeline = keras_ocr.pipeline.Pipeline()

Looking for C:\Users\OmerYildiz\.keras-ocr\craft_mlt_25k.h5
Looking for C:\Users\OmerYildiz\.keras-ocr\crnn_kurapan.h5


In [42]:
images = [keras_ocr.tools.read(img) for img in["test.jpg"]]

In [43]:
images

[array([[[160, 176, 202],
         [154, 170, 196],
         [156, 170, 197],
         ...,
         [153, 154, 185],
         [158, 159, 190],
         [157, 158, 189]],
 
        [[170, 182, 208],
         [158, 170, 196],
         [169, 181, 207],
         ...,
         [167, 162, 184],
         [171, 166, 188],
         [186, 181, 203]],
 
        [[144, 155, 177],
         [134, 145, 167],
         [131, 139, 162],
         ...,
         [157, 152, 174],
         [169, 164, 186],
         [150, 147, 168]],
 
        ...,
 
        [[118, 123, 129],
         [124, 127, 134],
         [128, 133, 139],
         ...,
         [142, 145, 152],
         [138, 138, 146],
         [154, 154, 162]],
 
        [[137, 142, 148],
         [145, 148, 155],
         [141, 146, 150],
         ...,
         [152, 153, 158],
         [146, 147, 152],
         [137, 136, 142]],
 
        [[142, 147, 153],
         [130, 133, 140],
         [132, 137, 141],
         ...,
         [130, 131, 135],
  

In [44]:
predictions = pipeline.recognize(images)

1/1 [==============================] - 2s 2s/step


In [45]:
predictions

[[('ivl',
   array([[466.,  40.],
          [489.,  40.],
          [489.,  57.],
          [466.,  57.]], dtype=float32)),
  ('d',
   array([[504.,  52.],
          [520.,  52.],
          [520.,  70.],
          [504.,  70.]], dtype=float32)),
  ('o',
   array([[441.,  54.],
          [458.,  54.],
          [458.,  69.],
          [441.,  69.]], dtype=float32)),
  ('808cc',
   array([[361.99997, 259.99997],
          [800.9999 , 259.99997],
          [800.9999 , 370.99997],
          [361.99997, 370.99997]], dtype=float32)),
  ('p',
   array([[233., 266.],
          [347., 266.],
          [347., 375.],
          [233., 375.]], dtype=float32)),
  ('ts',
   array([[157., 270.],
          [246., 270.],
          [246., 345.],
          [157., 345.]], dtype=float32)),
  ('221',
   array([[718., 387.],
          [750., 387.],
          [750., 407.],
          [718., 407.]], dtype=float32)),
  ('331',
   array([[777., 387.],
          [807., 387.],
          [807., 406.],
          [777.

In [46]:
import itertools

In [ ]:
fig, axs = plt.subplots(nrows = len(images), figsize= (18,18))
for ax,  prediction in zip(itertools.repeat(axs ,predictions)):
    keras_ocr.tools.drawAnnotations(image = images, predictions=prediction, ax=ax )